import { Product } from './types';

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Abstract Waves - Digital Download',
    description: 'High-resolution digital artwork featuring flowing abstract waves in warm tones. Perfect for prints, social media, or digital displays. Includes JPG and PNG formats at 300 DPI.',
    category: 'digital',
    price: 25,
    images: ['/products/project-1.svg'],
    isDigital: true,
    digitalFileUrl: '/downloads/abstract-waves.zip',
    featured: true,
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'prod_2',
    name: 'Modern Minimalist Print',
    description: 'Elegant minimalist design printed on premium matte paper. Clean lines and sophisticated color palette make this piece perfect for modern interiors.',
    category: 'print',
    price: 45,
    images: ['/products/project-2.svg'],
    variants: [
      {
        name: 'Size',
        options: [
          { value: '8x10', priceModifier: 0 },
          { value: '11x14', priceModifier: 30 },
          { value: '16x20', priceModifier: 75 },
        ],
      },
      {
        name: 'Format',
        options: [
          { value: 'Print Only', priceModifier: 0 },
          { value: 'Matted', priceModifier: 25 },
          { value: 'Framed', priceModifier: 60 },
        ],
      },
    ],
    isDigital: false,
    inventory: 50,
    featured: true,
    createdAt: new Date('2024-01-20').toISOString(),
  },
  {
    id: 'prod_3',
    name: 'Geometric Harmony Print',
    description: 'Bold geometric patterns in a harmonious color scheme. Museum-quality print on archival paper that will last for generations.',
    category: 'print',
    price: 55,
    images: ['/products/project-3.svg'],
    variants: [
      {
        name: 'Size',
        options: [
          { value: '8x10', priceModifier: 0 },
          { value: '11x14', priceModifier: 30 },
          { value: '16x20', priceModifier: 75 },
          { value: '24x36', priceModifier: 150 },
        ],
      },
    ],
    isDigital: false,
    inventory: 30,
    featured: false,
    createdAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'prod_4',
    name: 'Original Watercolor Artwork',
    description: 'One-of-a-kind original watercolor painting on cold-press paper. This unique piece features vibrant colors and expressive brushwork. Signed and dated by the artist. Includes certificate of authenticity.',
    category: 'original',
    price: 650,
    images: ['/products/project-4.svg'],
    isDigital: false,
    inventory: 1,
    featured: true,
    createdAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: 'prod_5',
    name: 'Custom Logo Design Service',
    description: 'Professional custom logo design tailored to your brand. Includes 3 initial concepts, 2 rounds of revisions, and final files in all formats (AI, EPS, PNG, SVG). Typical turnaround: 7-10 business days.',
    category: 'service',
    price: 300,
    images: ['/products/project-5.svg'],
    isDigital: true,
    featured: false,
    createdAt: new Date('2024-02-15').toISOString(),
  },
  {
    id: 'prod_6',
    name: 'Brand Identity Package',
    description: 'Complete brand identity design including logo, color palette, typography guidelines, business cards, and letterhead. Perfect for startups and rebrands.',
    category: 'service',
    price: 800,
    images: ['/products/project-6.svg'],
    isDigital: true,
    featured: true,
    createdAt: new Date('2024-02-20').toISOString(),
  },
  {
    id: 'prod_7',
    name: 'Sunset Landscape Print',
    description: 'Stunning landscape photograph capturing a breathtaking sunset. Printed on premium lustre photo paper with vibrant, true-to-life colors.',
    category: 'print',
    price: 65,
    images: ['/products/project-7.svg'],
    variants: [
      {
        name: 'Size',
        options: [
          { value: '11x14', priceModifier: 0 },
          { value: '16x20', priceModifier: 55 },
          { value: '24x36', priceModifier: 135 },
        ],
      },
      {
        name: 'Finish',
        options: [
          { value: 'Lustre', priceModifier: 0 },
          { value: 'Matte', priceModifier: 0 },
          { value: 'Canvas', priceModifier: 80 },
        ],
      },
    ],
    isDigital: false,
    inventory: 40,
    featured: false,
    createdAt: new Date('2024-02-25').toISOString(),
  },
  {
    id: 'prod_8',
    name: 'Design Consultation - 1 Hour',
    description: 'One-on-one design consultation via video call. Get expert advice on your design projects, brand strategy, or creative direction. Includes follow-up summary document.',
    category: 'service',
    price: 150,
    images: ['/products/project-8.svg'],
    isDigital: true,
    featured: false,
    createdAt: new Date('2024-03-01').toISOString(),
  },
  {
    id: 'prod_9',
    name: 'Original Mixed Media Artwork',
    description: 'Unique mixed media piece combining acrylic paint, ink, and collage elements. Mounted on gallery-wrapped canvas, ready to hang. This is a one-of-a-kind original artwork.',
    category: 'original',
    price: 850,
    images: ['/products/project-9.svg'],
    isDigital: false,
    inventory: 1,
    featured: true,
    createdAt: new Date('2024-03-05').toISOString(),
  },
  {
    id: 'prod_10',
    name: 'Botanical Series - Digital Bundle',
    description: 'Collection of 5 high-resolution botanical illustrations. Perfect for prints, cards, or digital use. Includes all files in multiple formats and sizes.',
    category: 'digital',
    price: 40,
    images: ['/products/project-1.svg'],
    isDigital: true,
    digitalFileUrl: '/downloads/botanical-bundle.zip',
    featured: false,
    createdAt: new Date('2024-03-10').toISOString(),
  },
];

export const categories = [
  { value: 'all', label: 'All Products' },
  { value: 'print', label: 'Prints' },
  { value: 'original', label: 'Originals' },
  { value: 'digital', label: 'Digital' },
  { value: 'service', label: 'Services' },
];
